package:
  name: modloader64-gui
  version: 4.0.1

source:
  fn: modloader64-gui-conda.zip
  url: ../dist/modloader64-gui-conda.zip

build:
  number: 2
  binary_relocation: False
  detect_binary_files_with_prefix: False
  include_recipe: False

about:
  home: http://modloader64.com
  license: GPL-3
  summary: GUI for ModLoader64