package:
  name: modloader64-gui-updater
  version: 3.0.0

source:
  fn: modloader64-gui-updater-conda.zip
  url: ../dist/modloader64-gui-updater-conda.zip

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  include_recipe: False

about:
  home: http://modloader64.com
  license: GPL-3
  summary: GUI updater for ModLoader64